In [1]:
print("Hello World")

Hello World


In [2]:
a=1
a

1

In [3]:
a=2
a

2

In [4]:
b=3.4
b

3.4

In [5]:
c=2+5j
c

(2+5j)

In [6]:
l=[1,2.3,3+5j,'suraj']
type(l)

list

In [7]:
t=(1,2.4,3+5j,'suraj')

In [8]:
type(t)

tuple

In [9]:
z=True
y=False

In [10]:
name="suraj veggalam"

In [11]:
n='suraj veggalam'

In [12]:
y='1'

In [13]:
y='2.3'

In [14]:
f='1+3j'

In [15]:
firstname='suraj'

In [16]:
firstname

'suraj'

In [17]:
first_name='suraj'
first_name

'suraj'

In [18]:
x="emmanuel"
x

'emmanuel'

In [19]:
type(x)

str

In [20]:
print(x)

emmanuel


In [21]:
len(x)

8

# indexing the strings
syntax=[start:stop:step]
accessing values inside the string

In [22]:
x='emmanuel'
x
x[0]

'e'

In [25]:
x[6]

'e'

In [26]:
x[7]

'l'

In [27]:
x[-1]

'l'

In [28]:
x[-2]

'e'

In [29]:
x[-7]

'm'

In [30]:
x[-8]

'e'

In [31]:
s="E mmanuel"
len(s)

9

In [32]:
s[2]

'm'

In [33]:
s[1]

' '

In [34]:
n='Anil'

In [35]:
len(n)

4

In [36]:
n[0]

'A'

In [37]:
n[1]

'n'

In [38]:
n[2]

'i'

In [39]:
n[3]

'l'

In [40]:
n[0:2]

'An'

In [41]:
n[0:4]

'Anil'

In [42]:
n="yaswanth"

In [43]:
n[2:5]

'swa'

In [44]:
n[4:8]

'anth'

In [45]:
s='Emmanuel'

In [46]:
print(s)

Emmanuel


In [47]:
s1='suraj'
s2='veggalam'

In [48]:
print(s1,s2)

suraj veggalam


In [49]:
s1

'suraj'

In [50]:
s2

'veggalam'

In [51]:
s1=1
s2=2
s1-s2

-1

In [52]:
s2-s1

1

In [53]:
w=s1+s2
w

3

In [54]:
a,b,c=1,2,3

In [55]:
a

1

In [56]:
b

2

In [57]:
c

3

In [58]:
a=b=c=100

In [59]:
a

100

In [61]:
b

100

In [62]:
c

100

In [63]:
g,h=20,30

In [64]:
g

20

In [65]:
h

30

In [66]:
x=y=z=200

In [67]:
x

200

In [68]:
y

200

In [69]:
z

200

In [70]:
a=1
b=2
a,b=b,a

In [71]:
a

2

In [72]:
b

1

In [73]:
s1="Emmanuel"
s2=" Mitra"

In [74]:
w=s1+s2
w

'Emmanuel Mitra'

In [75]:
a=1
b=2
a,b=b,a

In [76]:
a

2

In [77]:
b

1

In [78]:
x,y=1,300
x,y=y,x

In [79]:
x

300

In [80]:
y

1

In [81]:
a=100
b=20
a+b

120

In [82]:
a-b

80

In [83]:
b-a

-80

In [84]:
x=3

In [85]:
x+=4

In [86]:
x

7

In [87]:
x=0
x+=3
x

3

In [88]:
x="360DigitMg"

In [89]:
x

'360DigitMg'

In [90]:
x[9]

'g'

In [91]:
x.index('g')

5

In [92]:
x.index('6')

1

In [93]:
x.index('0')

2

In [94]:
x.index('i')

4

# what are the rule for assigning the valuables
1. should be start with numbers or special characters except'
2.cannot use space
3.prefer using small letters
4.avoid using words have special meaning in python like ,list, python, def, lambda.

In [95]:
a="India"

In [96]:
a[1:3]

'nd'

In [97]:
a.upper()

'INDIA'

In [98]:
a.lower()

'india'

In [99]:
a.capitalize()

'India'

In [100]:
a="India is a country with @ mutliple religions @ therefore it is secular"

In [101]:
a.split('@')

['India is a country with ',
 ' mutliple religions ',
 ' therefore it is secular']

In [102]:
a

'India is a country with @ mutliple religions @ therefore it is secular'

In [103]:
x=a.split('@')
x

['India is a country with ',
 ' mutliple religions ',
 ' therefore it is secular']

In [104]:
states='kar & maha & kerala & UP & MP'

In [105]:
states.split('&')

['kar ', ' maha ', ' kerala ', ' UP ', ' MP']

In [106]:
l=[1,2,3,4,5,6]

In [107]:
type(l)

list

In [108]:
l1=[1,2,'suraj','India',2+3j,True,False,2.6]

In [109]:
l1

[1, 2, 'suraj', 'India', (2+3j), True, False, 2.6]

In [110]:
type(l1)

list

In [111]:
l1[2:4]

['suraj', 'India']

In [112]:
l1[-1]

2.6

# operations on list

In [113]:
l=[1,2,3,4,5]

In [114]:
l.append(2999)

In [115]:
l

[1, 2, 3, 4, 5, 2999]

In [116]:
l.append("Mumbai")

In [117]:
l

[1, 2, 3, 4, 5, 2999, 'Mumbai']

In [118]:
l1=[1,2,3,4,5]
l2=['suraj','superhero','ironman','superman']


In [119]:
l1.append(l2)

In [120]:
l1

[1, 2, 3, 4, 5, ['suraj', 'superhero', 'ironman', 'superman']]

In [121]:
l1[1]

2

In [122]:
l1=[1,2,3,4,5]
l2=['suraj','superhero','ironman','superman']

In [123]:
l1.extend(l2)

In [124]:
l1

[1, 2, 3, 4, 5, 'suraj', 'superhero', 'ironman', 'superman']

In [125]:
e=[1,3,2,5,4,6]
e.insert(1,'suraj')

In [126]:
e

[1, 'suraj', 3, 2, 5, 4, 6]

In [127]:
e.insert(0,'india')
e

['india', 1, 'suraj', 3, 2, 5, 4, 6]

In [128]:
e.insert(-2,'hi')

In [129]:
e

['india', 1, 'suraj', 3, 2, 5, 'hi', 4, 6]

In [130]:
e.insert(9,"360DigitMg")
e

['india', 1, 'suraj', 3, 2, 5, 'hi', 4, 6, '360DigitMg']

In [131]:
e.insert(11,"suraj Veggalam")
e

['india', 1, 'suraj', 3, 2, 5, 'hi', 4, 6, '360DigitMg', 'suraj Veggalam']

In [132]:
l=[1,2,3,4,5,6,'name']

In [133]:
l.remove('name')

In [134]:
l

[1, 2, 3, 4, 5, 6]

In [135]:
l.remove(1)

In [136]:
l

[2, 3, 4, 5, 6]

In [137]:
l=['guj','tel','mah','madh']

In [138]:
l.pop()

'madh'

In [139]:
l.pop(0)

'guj'

In [140]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [141]:
l.reverse()

In [142]:
l

['mah', 'tel']

In [144]:
l=[2,1,3,5,4,7,6]
l.reverse()
l


[6, 7, 4, 5, 3, 1, 2]

In [145]:
x=l.copy()
x

[6, 7, 4, 5, 3, 1, 2]

In [148]:
x.sort()

In [149]:
x

[1, 2, 3, 4, 5, 6, 7]

In [150]:
l=['suraj','superman','ironman']
l.reverse()
l

['ironman', 'superman', 'suraj']

In [151]:
x=l.copy()
x

['ironman', 'superman', 'suraj']

In [152]:
print(l,x)

['ironman', 'superman', 'suraj'] ['ironman', 'superman', 'suraj']


In [154]:
l=[1,1,2,2,2,2,2,5,5]
l.count(1)


2

In [155]:
l.count(2)


5

In [156]:
l.count(5)

2

In [157]:
l=['suraj yadagiri veggalam']
l

['suraj yadagiri veggalam']

In [158]:
for i in l:
    print(l)

['suraj yadagiri veggalam']


# features of Tuples
#1.Ordered
#2.Immutable
#3.()
#4.Cannot be Changed
#5.It can hold many types of data
#6.Indexing is possible

In [159]:
t=('suraj','superman','thanos','blackwidow','doctor')
t

('suraj', 'superman', 'thanos', 'blackwidow', 'doctor')

In [160]:
t[2]

'thanos'

In [161]:
t[1]

'superman'

In [162]:
l=[1,1,2,2,2,2,2,5,5]

In [163]:
l[2]='suraj'

In [164]:
l

[1, 1, 'suraj', 2, 2, 2, 2, 5, 5]

In [165]:
t.count('suraj')

1

In [166]:
r=(1,1,1,3,4,5)

In [167]:
type(r)

tuple

# 1.Unordered
#2.Unindexed
#3.{}
#4.duplicates are not allowed
#5.{keys: values}
#6.Mutable

In [168]:
d={1:'suraj',2:'veggalam'}
d

{1: 'suraj', 2: 'veggalam'}

In [169]:
d.items()

dict_items([(1, 'suraj'), (2, 'veggalam')])

In [170]:
d.keys()

dict_keys([1, 2])

In [171]:
d.values()

dict_values(['suraj', 'veggalam'])

In [172]:
d1={'names':'suraj','age':20,'coursename':'Datascientist'}

In [173]:
d1.items()

dict_items([('names', 'suraj'), ('age', 20), ('coursename', 'Datascientist')])

In [174]:
d1.keys()

dict_keys(['names', 'age', 'coursename'])

In [175]:
d1.values()

dict_values(['suraj', 20, 'Datascientist'])

In [176]:
d1['names']='kiran'

In [177]:
d1

{'names': 'kiran', 'age': 20, 'coursename': 'Datascientist'}

In [178]:
d1['age']=30

In [179]:
d1

{'names': 'kiran', 'age': 30, 'coursename': 'Datascientist'}

In [180]:
d2={'name':'superman','planet':'earth','age':'50'}

In [181]:
d2.items()

dict_items([('name', 'superman'), ('planet', 'earth'), ('age', '50')])

In [182]:
d2.keys()

dict_keys(['name', 'planet', 'age'])

In [183]:
d2.values()

dict_values(['superman', 'earth', '50'])

In [184]:
print(type(d2))

<class 'dict'>


In [185]:
d2.items()

dict_items([('name', 'superman'), ('planet', 'earth'), ('age', '50')])

In [186]:
d2.keys()

dict_keys(['name', 'planet', 'age'])

In [187]:
d2.values()

dict_values(['superman', 'earth', '50'])

In [188]:
d2={'names' :['superman','ironman'], 'planet':['earth','jupiter'], 'age':['50','40']}

In [189]:
d2.items()

dict_items([('names', ['superman', 'ironman']), ('planet', ['earth', 'jupiter']), ('age', ['50', '40'])])

In [190]:
d2.keys()

dict_keys(['names', 'planet', 'age'])

In [191]:
d2.values()

dict_values([['superman', 'ironman'], ['earth', 'jupiter'], ['50', '40']])

In [192]:
d2['names']

['superman', 'ironman']

In [193]:
d2['age']

['50', '40']

In [194]:
d2['planet']

['earth', 'jupiter']

In [195]:
d2['names'][1]

'ironman'

In [196]:
d2['planet'][1]

'jupiter'

In [197]:
d2['age'][1]

'40'

# Features of sets
#1.Unordered
#2.contains unique elements
#3.Duplication is not allowed
#4.unindexed
#5.Indexing is not possible

In [198]:
s={1,2,3,4,5}

In [199]:
type(s)

set

In [200]:
s1={1,2,1,1,1,3,4,2,6,7}

In [201]:
s1

{1, 2, 3, 4, 6, 7}

In [202]:
s2={'suraj','veggalam','superman','spyderman'}

In [203]:
s3=s1.intersection(s2)

In [204]:
s3

set()

In [205]:
s1={1,2,3,4,5}
s2={1,8,9,0,2}
s1.intersection(s2)

{1, 2}

In [206]:
s1

{1, 2, 3, 4, 5}

In [207]:
s1={1,2,3,4,5,9}
s2={4,5,1,3,10,2}
s1.intersection(s2)

{1, 2, 3, 4, 5}

In [208]:
s1

{1, 2, 3, 4, 5, 9}

# Arthematic Operators
#+
#-
#*
#%

In [209]:
a=10
b=1
a+b

11

In [210]:
a-b

9

In [211]:
a*b

10

In [212]:
x=4
y=2
x/y

2.0

In [213]:
#floordivision
x//2

2

In [214]:
a=4
b=2
a**b

16

# Comparison Operators

In [215]:
a=1
b=2


In [216]:
a==1

True

In [217]:
a==2

False

In [218]:
b==2

True

In [219]:
b==1

False

In [220]:
a>b

False

In [221]:
a<b

True

In [222]:
b>a

True

In [223]:
b<a

False

In [224]:
a!=b

True

In [225]:
b!=a

True

# Assignment Operators

In [226]:
a=1
b=2


In [227]:
c=a+b
c

3

In [228]:
c+=b

In [229]:
c

5

In [230]:
c=3
b=4

In [231]:
c+=b

In [232]:
c

7

In [233]:
a=3
b=8
a-=b

In [234]:
a

-5

In [235]:
b

8

In [236]:
a=3
b=4
a*=b
a

12

# Membership Operators

In [237]:
'suraj'

'suraj'

In [238]:
's' in 'suraj'

True

In [239]:
'u' in 'suraj'

True

In [240]:
'S' in 'suraj'

False

In [241]:
'python'

'python'

In [242]:
'y' not in 'python'

False

In [243]:
'y' in 'python'

True

In [244]:
a=1

In [245]:
a is 1

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\sony\AppData\Local\Temp\ipykernel_139940\3222642818.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  a is 1


True

In [246]:
1 is a

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\sony\AppData\Local\Temp\ipykernel_139940\3892644797.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  1 is a


True

In [247]:
a=2

In [248]:
a is 2

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\sony\AppData\Local\Temp\ipykernel_139940\135120866.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  a is 2


True

In [249]:
2 is a 

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\sony\AppData\Local\Temp\ipykernel_139940\1403096933.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  2 is a


True

In [250]:
A=1
1 is A

<>:2: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:2: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\sony\AppData\Local\Temp\ipykernel_139940\662119662.py:2: SyntaxWarning: "is" with a literal. Did you mean "=="?
  1 is A


True

In [251]:
a=2 
2 is a

<>:2: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:2: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\sony\AppData\Local\Temp\ipykernel_139940\476202593.py:2: SyntaxWarning: "is" with a literal. Did you mean "=="?
  2 is a


True

In [252]:
a=1
a is not 1

<>:2: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:2: SyntaxWarning: "is not" with a literal. Did you mean "!="?
C:\Users\sony\AppData\Local\Temp\ipykernel_139940\513449240.py:2: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  a is not 1


False

# String Formatting

In [253]:
a="this is python class"

In [254]:
a

'this is python class'

In [255]:
type(a)

str

In [256]:
'my name is %s and age is %d '%('suraj',22)

'my name is suraj and age is 22 '

In [257]:
'my name is %s and age is %d '%('superhero',25)

'my name is superhero and age is 25 '

In [258]:
'my name is %s and age is %d '%('mayur',29)

'my name is mayur and age is 29 '

In [259]:
'my name is %s and age is %d '%('superman',98)

'my name is superman and age is 98 '

# how to take input from user

In [261]:
name=input('enter your name')
age=input('enter your age')

enter your namesuraj
enter your age98


In [262]:
name = input('enter your name')

enter your namekamala Yadagiri Veggalam


In [263]:
age = input('enter your age')

enter your age49


In [264]:
type(name)

str

In [265]:
type(age)

str

In [267]:
age=int(input('enter your age '))

enter your age 16


In [271]:
'%s my name is and age is %d '%('superman',88)

'superman my name is and age is 88 '

In [272]:
'%s my name is and age is %d '%('suraj',25)

'suraj my name is and age is 25 '

In [273]:
name = input('enter your name')

enter your namesuraj


In [274]:
name = input('enter your name ')

enter your name suraj y veggalam


In [275]:
name = input('enter your name: ')
age=int(input('enter your age  '))
print('your name is %s and your age is %d' %(name,age))

enter your name: kamala y veggalam
enter your age  51
your name is kamala y veggalam and your age is 51


In [1]:
name = input('enter your name')
age =input('enter your age')
print('your name is {} and your age is {}' .format(name,age))

enter your namesuraj
enter your age25
your name is suraj and your age is 25


In [2]:
name =input('enter your name ')
age =input('enter your age')
print('your name is {} and your age is {}' .format(name,age))

enter your name suraj y vegga
enter your age28
your name is suraj y vegga and your age is 28


In [3]:
name =input('enter your name ')
age =input('enter your age ')
print('your name is {} and your age is {}' .format(name,age))

enter your name 
  @media print {
    .ms-editor-squiggles-container {
      display:none !important;
    }
  }
  .ms-editor-squiggles-container {
    all: initial;
  }kiran shirkul
enter your age 25
your name is kiran shirkul and your age is 25


In [4]:
def xyz():
    
    name =input('enter your name ')
    age =input('enter your age ')
    print('your name is {1} and your age is {0}' .format(name,age))

In [6]:
name =input('enter your name: ')
age =input('enter your age: ')
weight =input('enter your weight: ')
print('your name is {} and your age is {}' .format(name,age,weight))

enter your name: suraj 
enter your age: 28
enter your weight: 70
your name is suraj  and your age is 28


In [7]:
name =input('enter your name: ')
age =input('enter your age: ')
weight =input('enter your weight: ')
print('your name is {} and your age is {} and your weight is {}' .format(name,age,weight))

enter your name: 
  @media print {
    .ms-editor-squiggles-container {
      display:none !important;
    }
  }
  .ms-editor-squiggles-container {
    all: initial;
  }mayur mirajgaonkar
enter your age: 25
enter your weight: 70
your name is mayur mirajgaonkar and your age is 25 and your weight is 70


In [8]:
name = input('enter your name: ')
age =input('enter your age: ')
wight =input('enter your weight: ')
print('your name is {} and your age is {} and your weight is {}kgs' .format(name,age,weight))

enter your name: 
  @media print {
    .ms-editor-squiggles-container {
      display:none !important;
    }
  }
  .ms-editor-squiggles-container {
    all: initial;
  }ganesh shahapurkar
enter your age: 35
enter your weight: 80
your name is ganesh shahapurkar and your age is 35 and your weight is 70kgs


In [10]:
name =input('enter your name: ')
weight =input('enter your weight: ')
print(f'{name} is {weight}kgs')

enter your name: suraj y veggalam
enter your weight: 31
suraj y veggalam is 31kgs


In [11]:
username =input('Enter username: ')
print('Username is: ' + username)

Enter username: suraj y veggalam
Username is: suraj y veggalam


In [12]:
username =input('Enter username: ')
print('Username is: '+ username)

Enter username: 
  @media print {
    .ms-editor-squiggles-container {
      display:none !important;
    }
  }
  .ms-editor-squiggles-container {
    all: initial;
  }Mayuresh v mirajgoankar
Username is: Mayuresh v mirajgoankar


In [13]:
val = input('Enter your value: ')
print(val)

Enter your value: suraj y veggalam
suraj y veggalam


In [14]:
name =input('What is your name?\n')       #\n------> newline   ---> It cauuses a line break
print(name)

What is your name?
suraj y veggalam
suraj y veggalam


# Program to check input
# type in Python

In [15]:
number =input('Enter number : ')
print(number)

name1 =input('Enter name : ')
print(name1)


## Printing type of input value
print('type of number', type(number))
print('type of name', type(name1))

Enter number : suraj y veggalam
suraj y veggalam
Enter name : 123
123
type of number <class 'str'>
type of name <class 'str'>


In [18]:
num =int(input("Enter your number: "))
print(num, " ", type(num))

floatNum = float(input("Enter a decimal number: "))
print(floatNum, " ", type(floatNum))

Enter your number: 54
54   <class 'int'>
Enter a decimal number: 1000.001
1000.001   <class 'float'>


In [19]:
num1 = int(input())
num2 = int(input())

print(num1+num2)

80
20
100


In [21]:
num1 =int(input())
num2 =int(input())

print(num1*num2)

25
4
100


In [22]:
string = str(input())

print(string)

string_default = input()

print(string_default)

akash
akash
raju
raju


# Python program showing how to
# multiple input using split
  
# taking two inputs at a time

In [24]:
x ,y = input("Enter two values: ").split()

print('Number of boys: ',x)
print('Number of girls: ',y)

print()

Enter two values: 25 25
Number of boys:  25
Number of girls:  25



# taking three inputs at a time

In [ ]:
# x,y,z = input("Enter three values: ").split()

print('Total number of students: ',x)
print('Number of boys is: ',y)
print('Number of girls is: ',z)

print()

# taking two inputs at a time

In [29]:
a , b = input("Enter two values: ").split()

print("First number is {} and and second number is {}" .format(a,b))

Enter two values: 20 30
First number is 20 and and second number is 30


# taking multiple inputs at a time 
# and type casting using list() function

In [30]:
x = list(map(int, input('Enter multiple values: ').split()))

print("List of students: ",x)

Enter multiple values: 100 25 80 180 111 125 68 96
List of students:  [100, 25, 80, 180, 111, 125, 68, 96]


# Python program showing
# how to take multiple input
# using List comprehension

In [37]:
# taking two input at a time

x,  y= [int(x) for x in input("Enter two values: ").split()]

print("First Number is: ",x)
print("Second Number is: ",y)
print()


Enter two values: 5 3
First Number is:  5
Second Number is:  3



# taking three input at a time

In [38]:


x,y,z =[int(x) for x in input("Enter three values: ").split()]
print("First Number is: ",x)
print("Second Number is: ",y)
print("Third Number is: ",z)

print()

Enter three values: 100 120 150
First Number is:  100
Second Number is:  120
Third Number is:  150



# taking two inputs at a time



In [39]:
x,y = [int(x) for x in input("Enter two values: ").split()]

print("First number is {} and second number is {}".format(x,y))
print()

Enter two values: 20 80
First number is 20 and second number is 80



# taking multiple inputs at a time

In [40]:
x = [int(x) for x in input ("Enter multiple values: ").split()]

print("Number of list is: ",x)

Enter multiple values: 10 20 30 40 50 60 70 80 90 100 110 120 130 140 150 160 
Number of list is:  [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160]


# taking multiple inputs at a time separated by comma

In [4]:
x =[int(x) for x in input("Enter multiple value: ").split(",")]

print("Number of list is: ",x)

Enter multiple value: 10
Number of list is:  [10]


# Python code to demonstrate a dictionary
# with multiple inputs in a key.

In [5]:
import random as rn

# creating an empty dictionary
dict = {}

# Insert first triplet in dictionary
x, y, z = 10, 20, 30
dict[x, y, z] = x + y - z;

# Insert second triplet in dictionary
x, y, z = 5, 2, 4
dict[x, y, z] = x + y - z;

# print the dictionary
print(dict)


{(10, 20, 30): 0, (5, 2, 4): 3}


In [ ]:
total_input = []

print("Enter Student Names: ")

while True:
    name=input()
    if name:
        total_input.append(name)
    else:
        break
        

        
print("Total input received: ")
print(total_input)

Enter Student Names: 
suraj
kiran
mayur
akash
chandru
ganesh
ajinkya
mahesh
aks
dhanraj
sagar
vishwaesh
piyush


In [ ]:
d = {}
count = 0
data = int(input("How many data do you want to enter?(numbers only): "))
while count < data:
    count = count + 1
    print("Enter a key")
    key = input()
    print("Enter a value")
    value = input()
    d[key] = value
    if count >= data:
        break

print(d)

How many data do you want to enter?(numbers only): 30
Enter a key
1
Enter a value
1
Enter a key
1
Enter a value
2
Enter a key
3
Enter a value
5
Enter a key
1
Enter a value
5
Enter a key
1
Enter a value
1
Enter a key
5
Enter a value
5
Enter a key
6
Enter a value
7
Enter a key
8
Enter a value
10
Enter a key
10
Enter a value
11
Enter a key
1111
Enter a value


In [ ]:
record = int(input("Enter the student record need to add :"))

stud_data={}

for i in range(0,record):
    Name = input("Enter the student name :").split()
    Age = input("Enter the {} age :".format(Name))
    Grade = input("Enter the {} grade :".format(Name)).split()
    Nam_key =  Name[0]
    Age_value = Age[0]
    Grade_value = Grade[0]
    stud_data[Nam_key] = {Age_value,Grade_value}

# Checking the Keys and Values from dictionary by Giving the input 

In [3]:
d = {"MumbaiIndians":"Mumbai","ChennaiSuperKings":"Chennai","KingsElevenPunjab":"Punjab","RajasthanRoyals":"Rajasthan","RoyalChallengersBangalore":"Bangalore","KolkataKnightRiders":"Kolkata","SunrisersHyerabad":"Hyderabad","DelhiCapitals":
     "Delhi","GujratTitans":"Gujrat","LucknowSuperGiants":"Lucknow"}


In [4]:
a=input("Enter the key: ")
b=input('Enter the item: ')
help(dict)

for i,j in d.keys() and d.items():
    if i == a : 
        print('key is True')
        if j == b:
            print('item True')
        else:
            print('item False')
    else:
        pass
        print('key and item is not matched')

Enter the key: MumbaiIndians
Enter the item: Mumbai
Help on class dict in module builtins:

class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |  
 |  Built-in subclasses:
 |      StgDict
 |  
 |  Methods defined here:
 |  
 |  __contains__(self, key, /)
 |      True if the dictionary has the specified key, else False.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem

# conditional Statements
#whenever your passing conditional statements you have to give :
elif used to check multiple statements

In [ ]:
if
else
elif

are the conditional statements

In [6]:
is_male = True

In [8]:
if is_male:
    print('your male')
else:
    print('your female')

your male


In [10]:
is_male=True
is_tall=False

In [11]:
if is_male and is_tall:
    print("you are tall male")
else:
    print("you are input is not correct")

you are input is not correct


In [12]:
num=10

if num>=10:
    print('number is large')
else:
    print('number is small')

number is large


In [13]:
is_male=True
is_tall=False

In [14]:
if is_male and is_tall:
    print("tall male")
elif is_male and not(is_tall):
    print("you are short male")
elif not(is_male) and is_tall:
    print("you are male but tall")
else:
    print("you are not male and not tall")

you are short male


In [15]:
if is_male and is_tall:
    print("tall male")
elif is_male and not(is_tall):
    print("you are short male")
else:
    print("you are not male and not tall")
    

you are short male


# Taking the Prime Numbers from the list with help of for loop

In [16]:
l=[1,2,3,4,5,6,6,7,8,9,10,11,12,13,14,15,16]

for i in l:
    if i%2==0:
        print(i)

2
4
6
6
8
10
12
14
16


# Taking the Odd Numbers from the list with the help for Loop

In [23]:
l=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]

for i in l:
    if i%2==1:
        print(i)

1
3
5
7
9
11
13
15
17
19
21
23
25


# List comprehension
list comprehension in Python is an easy and compact syntax for creating a list from a string or another list. it is a very concise way to create a new list by performing an operation on each item in the existing list.
List comprehension is considerably faster than processing a list using the for loop 


In [24]:
# Normal For Loop

l=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

for i in l:
    print(i)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


# list Comprehension

In [25]:
[i for i in l]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

# Add The numbers to list with help of list Comprehension

In [26]:
[i+100 for i in l]

[101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115]

# Multipling the Numbers to list with help of list Comprehension

In [27]:
[i*2 for i in l]

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]

# Subracting the numbers to list with of list Comprehension

In [28]:
[i-0.5 for i in l]

[0.5,
 1.5,
 2.5,
 3.5,
 4.5,
 5.5,
 6.5,
 7.5,
 8.5,
 9.5,
 10.5,
 11.5,
 12.5,
 13.5,
 14.5]

In [29]:
[i-1 for i in l]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [31]:
marks =[52,60,70,48,78,85]

In [32]:
[i/100*2 for i in l]

[0.02,
 0.04,
 0.06,
 0.08,
 0.1,
 0.12,
 0.14,
 0.16,
 0.18,
 0.2,
 0.22,
 0.24,
 0.26,
 0.28,
 0.3]

In [33]:
[i+123 for i in l]

[124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138]

In [ ]:
## String Comprehension

In [35]:
n="suraj"

[i for i in n]

['s', 'u', 'r', 'a', 'j']

In [37]:
m="Sachin Tendulkar was the Greatest batsmen of indian but Now Virat Koli is the best Batsmen"

[i for i in m]

['S',
 'a',
 'c',
 'h',
 'i',
 'n',
 ' ',
 'T',
 'e',
 'n',
 'd',
 'u',
 'l',
 'k',
 'a',
 'r',
 ' ',
 'w',
 'a',
 's',
 ' ',
 't',
 'h',
 'e',
 ' ',
 'G',
 'r',
 'e',
 'a',
 't',
 'e',
 's',
 't',
 ' ',
 'b',
 'a',
 't',
 's',
 'm',
 'e',
 'n',
 ' ',
 'o',
 'f',
 ' ',
 'i',
 'n',
 'd',
 'i',
 'a',
 'n',
 ' ',
 'b',
 'u',
 't',
 ' ',
 'N',
 'o',
 'w',
 ' ',
 'V',
 'i',
 'r',
 'a',
 't',
 ' ',
 'K',
 'o',
 'l',
 'i',
 ' ',
 'i',
 's',
 ' ',
 't',
 'h',
 'e',
 ' ',
 'b',
 'e',
 's',
 't',
 ' ',
 'B',
 'a',
 't',
 's',
 'm',
 'e',
 'n']

# Checking the numbers in the list with the help of Boolean 

In [38]:
l=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]

[i%2==0 for i in l]

[False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False]

# Checking the Odd Numbers in the list with the help of list comprehension and Output Come Boolean

In [39]:
l=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]

[i%2==1 for i in l]

[True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False]

# Checking the prime numbers in the List with list Comprehension by if statement 

In [40]:
l=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

[i for i in l if i%2==0]

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

# Checking the Odd numbers in the List with list Comprehension by if statement 

In [41]:
l=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]

[i for i in l if i%2==1]

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]

# Add the Numbers to list with list comprehension by giving if statement

In [42]:
l=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]

[i+10 for i in l if i%2==0]

[12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34]

In [43]:
for i in l:
    if i%2==0:
        print(i+11)

13
15
17
19
21
23
25
27
29
31
33
35


In [44]:
l=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

for i in l:
    if i>5:
        print("large number")
    else:
        print("small number")

small number
small number
small number
small number
small number
large number
large number
large number
large number
large number
large number
large number
large number
large number
large number
large number
large number
large number
large number
large number


In [45]:
l=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

[i for i in l if i>6]

[7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [46]:
['largenumber' for i in l if i>5]

['largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber']

In [47]:
['large' if i>5 else 'small' for i in l]

['small',
 'small',
 'small',
 'small',
 'small',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large']

In [48]:
['large' if i>5 else 'small' for i in l]

['small',
 'small',
 'small',
 'small',
 'small',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large',
 'large']

In [49]:
['largenumber' for i in l if i>=5]

['largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber',
 'largenumber']

In [50]:
l=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

[1 if i>5 else 0 for i in l]

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [51]:
l=['male','male','male','female','female','female','female']

[0 if i== 'male' else 1 for i in l]

[0, 0, 0, 1, 1, 1, 1]

# While Loop 
# always you have to give :

In [52]:
while i>0:
    print(i)
    i=i-1

20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1


In [56]:
def who_you_are():
    is_male=False
    is_tall=True
    if is_male and is_tall:
        print("you are BAHUBALI")
    else:
        print("your are KHATAPPA")

In [57]:
who_you_are()

your are KHATAPPA


In [59]:
def suraj():
    name=input('enter your name')
    age=int(input('enter your age'))
    print(f'your name is {name} and your age is {age}')
    return(age)
    return(name)


In [60]:
suraj()

enter your namesuraj y vegga
enter your age28
your name is suraj y vegga and your age is 28


28

In [1]:
def suraj():
    name=input("enter your name: ")
    age=int(input("enter your age: "))
    weight =int(input('enter your weight: '))
    print(f"your name is {name} and your age is {age} and your weight is {weight}")
    return(age)
    return(name)
    return(weight)



In [2]:
suraj()

enter your name: suraj y veggalam
enter your age: 21
enter your weight: 73
your name is suraj y veggalam and your age is 21 and your weight is 73


21

In [3]:
def suraj():
    name=input("enter your name: ")
    age=int(input("enter your age: "))
    weight =int(input('enter your weight: '))
    print(f"your name is {name} and your age is {age} and your weight is {weight}")
    return(age)
    return(name)
    return(weight)



In [4]:
suraj()

enter your name: suraj y veggalam
enter your age: 29
enter your weight: 79
your name is suraj y veggalam and your age is 29 and your weight is 79


29

In [5]:
l=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

def evenid(l):
    for i in l:
        if i%2==0:
            print(i)

In [7]:
evenid(l)

2
4
6
8
10
12
14
16
18
20


In [8]:
def evenid(l):
    for i in l:
        if i%2==1:
            print(i)

In [9]:
evenid(l)

1
3
5
7
9
11
13
15
17
19


In [13]:
f = lambda x: x%2==0

In [14]:
f

<function __main__.<lambda>(x)>

In [15]:
list(map(f,l))

[False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True]

In [16]:
f=lambda x: x%2==1
f

list(map(f,l))

[True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False]

In [17]:
f=lambda x: x**2
f

list(map(f,l))

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400]

In [18]:
f=lambda x: x++1
f

list(map(f,l))

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [19]:
f=lambda x: x-1
f

list(map(f,l))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [21]:
l=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

f=lambda x: x+10

f

tuple(map(f,l))

(11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30)

In [22]:
f =lambda x: x+100

f

set(map(f,l))

{101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120}

In [24]:
f =lambda x: x*100

f

list(map(f,l))

[100,
 200,
 300,
 400,
 500,
 600,
 700,
 800,
 900,
 1000,
 1100,
 1200,
 1300,
 1400,
 1500,
 1600,
 1700,
 1800,
 1900,
 2000]

In [1]:
l=[1,2,3,4,5,6]

f=lambda s: str(s)

ls = list(map(f,l))

type(ls[1])

str

# Pandas are used to create dataframe and manipulte with dataframe and play with dataframe

In [2]:
import pandas as pd

In [4]:
l1=[1,2,3,4,5]
l2=[122,133,144,155,166]
l3=[200,300,400,500,600]

df = pd.DataFrame(columns=['names','Marks','RollNo.'])

df['names']=l1
df['Marks']=l2
df['RollNo.']=l3

df

names  Marks  RollNo.
0      1    122      200
1      2    133      300
2      3    144      400
3      4    155      500
4      5    166      600

# how to convert dictionary to Dataframe

In [5]:
d= {'names':['suraj','superman','ironman','krish'],'age':[22,23,24,25]}

d.keys()

dict_keys(['names', 'age'])

In [6]:
df=pd.DataFrame(d)

In [7]:
df

names  age
0     suraj   22
1  superman   23
2   ironman   24
3     krish   25

In [8]:
df.tail()

names  age
0     suraj   22
1  superman   23
2   ironman   24
3     krish   25

In [9]:
df.head()

names  age
0     suraj   22
1  superman   23
2   ironman   24
3     krish   25

In [10]:
df['Marks']=[22,33,44,55]

In [11]:
df

names  age  Marks
0     suraj   22     22
1  superman   23     33
2   ironman   24     44
3     krish   25     55

In [12]:
df['Subject']=['Statistics','Mathematics','Physics','Chemistry']
df

names  age  Marks      Subject
0     suraj   22     22   Statistics
1  superman   23     33  Mathematics
2   ironman   24     44      Physics
3     krish   25     55    Chemistry

In [13]:
df['Total']=[100,100,100,100]
df

names  age  Marks      Subject  Total
0     suraj   22     22   Statistics    100
1  superman   23     33  Mathematics    100
2   ironman   24     44      Physics    100
3     krish   25     55    Chemistry    100

In [14]:
df['percentage']=[98,88,77,44]
df

names  age  Marks      Subject  Total  percentage
0     suraj   22     22   Statistics    100          98
1  superman   23     33  Mathematics    100          88
2   ironman   24     44      Physics    100          77
3     krish   25     55    Chemistry    100          44

In [15]:
import pandas as pd

In [16]:
l=[1,2,3,4,5,6,7]

In [17]:
s=pd.Series(l)
type(s)

pandas.core.series.Series

In [18]:
t=(4,5,6,7,8,9)

s1=pd.Series(t)

type(s1)
print(s1)
print(s)

0    4
1    5
2    6
3    7
4    8
5    9
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64


In [19]:
pd.DataFrame(s,s1)

0
4  5.0
5  6.0
6  7.0
7  NaN
8  NaN
9  NaN

In [20]:
import pandas as pd

In [21]:
df=pd.DataFrame(columns=['names','PhoneNo.'])

In [22]:
df

Empty DataFrame
Columns: [names, PhoneNo.]
Index: []

# group By Function

In [23]:
import pandas as pd

dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__deprecated_num_index_names',
 '__dir__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_testing',
 '_typing',
 '_ve

In [24]:
import numpy as np

x=[1,2,3,4,5]

x*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [25]:
y=np.array(x)

In [26]:
y

array([1, 2, 3, 4, 5])

In [28]:
type(y)

numpy.ndarray

In [29]:
y3=y+100
print(y3)



[101 102 103 104 105]


# one dimensional Array

In [30]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [31]:
type(a)

numpy.ndarray

# creating two dimensionl Array

In [32]:
b=np.array([(1,2,3,4,5),(6,7,8,9,10)])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# creating three dimensionl Array

In [34]:
c=np.array([(1,2,3,4,5),(6,7,8,9,10),(11,12,13,14,15)])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

# creating Four dimensionl Array

In [35]:
d=np.array([(1,2,3,4,5),(6,7,8,9,10),(11,12,13,14,15),(16,17,18,19,20)])

d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# Creating Numpy array with the help of range function

In [36]:
c=np.arange(1,10,2)
c

array([1, 3, 5, 7, 9])

In [37]:
c=np.arange(1,10,1)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
c=np.arange(1,10,-1)
c

array([], dtype=int32)

In [41]:
c=np.arange(1,20,1.5)
c

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. , 11.5, 13. , 14.5, 16. ,
       17.5, 19. ])

# Create numpy Array filled with Zero's

In [42]:
np.zeros((1,2,3))


array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [43]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
np.zeros((3,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
np.zeros((4,20))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

# Create Numpy Array filled with ones 

In [46]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [47]:
np.ones((6,20))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

# Create Empty Array 

In [48]:
np.random.random((5,5))

array([[0.19305392, 0.01746153, 0.27256349, 0.5172666 , 0.60106578],
       [0.02553248, 0.47232939, 0.50531903, 0.2687835 , 0.9523102 ],
       [0.44056428, 0.60064638, 0.45081342, 0.25358062, 0.53068372],
       [0.81728458, 0.63516442, 0.77529183, 0.40990423, 0.43399679],
       [0.93202989, 0.54996504, 0.4407757 , 0.3469478 , 0.38778589]])

# Add Evenly spaced values between intervalues of arrays of length

In [50]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [51]:
np.linspace(0,2,15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [52]:
print(4)

4


In [53]:
len(a)

5

In [54]:
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [55]:
type(b)

numpy.ndarray

In [56]:
a.dtype

dtype('int32')

In [57]:
b.dtype

dtype('int32')

# Numpy Matrix

In [58]:
#how to create a numpy matrix.

np.matrix('1 2;3 4')

matrix([[1, 2],
        [3, 4]])

In [59]:
np.matrix('1 20;21 40')

matrix([[ 1, 20],
        [21, 40]])

In [60]:
np.matrix('1 2 3 4; 5 6 7 8; 9 10 11 12; 13 14 15 16; 17 18 19 20')

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]])

In [61]:
# 2 method numpy matrix

np.matrix([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])

matrix([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])

In [62]:
b.shape

(2, 5)

# Create sequence of integers with the specific values 

In [63]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [64]:
np.arange(1,50,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [65]:
np.arange(1,120,12)

array([  1,  13,  25,  37,  49,  61,  73,  85,  97, 109])

In [71]:
# Difference between arange and range 

f=np.arange(0,50,5)
print(f)

[ 0  5 10 15 20 25 30 35 40 45]


In [72]:
np.arange(0,50,5)
print(f)
type(f)

[ 0  5 10 15 20 25 30 35 40 45]


numpy.ndarray

In [73]:
f=tuple(range(0,50,5))
print(f)
type(f)

(0, 5, 10, 15, 20, 25, 30, 35, 40, 45)


tuple

In [2]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.delete(a,0,axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [4]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.delete(a,1,axis=1)

array([[1, 3],
       [4, 6],
       [7, 9]])

In [7]:
b= np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.delete(b,2,axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

# Reshaping the array

In [9]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
c.shape

(3, 3)

In [11]:
c[1]

array([4, 5, 6])

In [12]:
c[0]

array([1, 2, 3])

In [13]:
c[0:1]

array([[1, 2, 3]])

In [14]:
c[1]

array([4, 5, 6])

In [15]:
c[2]

array([7, 8, 9])

In [16]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
c[0,1]

2

In [18]:
c[1,1]

5

In [19]:
c[2,1]

8

In [20]:
c=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,100],])

In [21]:
c

array([[  1,   2,   3,   4],
       [  4,   5,   6,   7],
       [  7,   8,   9, 100]])

In [22]:
c3=c.reshape(6,2)

In [23]:
c3

array([[  1,   2],
       [  3,   4],
       [  4,   5],
       [  6,   7],
       [  7,   8],
       [  9, 100]])

In [24]:
c3.flatten()

array([  1,   2,   3,   4,   4,   5,   6,   7,   7,   8,   9, 100])

# end of the numpy

# matplotlib Package
matplotlib is a package which is used for the visualization purpose

In [ ]:
import matplotlib.pyplot as plt
plt.hist()


# Enumerate function with list

In [26]:
l=['suraj','superman','spyderman','krish','ironman']
for i in enumerate(l):
    print(i)

(0, 'suraj')
(1, 'superman')
(2, 'spyderman')
(3, 'krish')
(4, 'ironman')


In [27]:
for i, j in enumerate(l):
    print(j)

suraj
superman
spyderman
krish
ironman


In [28]:
for i, j in enumerate(l):
    print(i)

0
1
2
3
4


In [29]:
l

['suraj', 'superman', 'spyderman', 'krish', 'ironman']

In [31]:
for i , j in enumerate(l):
    if i>2:
        print(i,j)

3 krish
4 ironman


In [32]:
for i, j in enumerate(l):
    if i==1:
        print(j)

superman


In [33]:
for i, j in enumerate(l , start=0):
    print(i)

0
1
2
3
4


In [34]:
for i in enumerate(l,start=1):
    print(i)

(1, 'suraj')
(2, 'superman')
(3, 'spyderman')
(4, 'krish')
(5, 'ironman')


In [35]:
for i,j in enumerate(l,start=0):
    print(j)


suraj
superman
spyderman
krish
ironman


In [36]:
for i, j in enumerate(l,start=1):
    print(i)

1
2
3
4
5


In [37]:
for i , j in enumerate(l,start=5):
    print(i)

5
6
7
8
9


In [38]:
for i, j in enumerate(l,start=5):
    print(j,i)

suraj 5
superman 6
spyderman 7
krish 8
ironman 9


In [39]:
for i, j in enumerate(l,start=5):
    print(i,j)

5 suraj
6 superman
7 spyderman
8 krish
9 ironman


In [40]:
for i in enumerate(l,start=5):
    print(i)

(5, 'suraj')
(6, 'superman')
(7, 'spyderman')
(8, 'krish')
(9, 'ironman')


In [41]:
for i, j in enumerate(l,start=100):
    print(j,i)


suraj 100
superman 101
spyderman 102
krish 103
ironman 104


In [42]:
for i,j in enumerate(l):
    print(j,i)


suraj 0
superman 1
spyderman 2
krish 3
ironman 4


# Enumeration function with tuple

In [43]:
t = ("superman","spyderman","hero","zero","thanos","thar")
t

for i in enumerate(t):
    print(i)

(0, 'superman')
(1, 'spyderman')
(2, 'hero')
(3, 'zero')
(4, 'thanos')
(5, 'thar')


In [44]:
for i in enumerate(t,start=1):
    print(i,j)

(1, 'superman') ironman
(2, 'spyderman') ironman
(3, 'hero') ironman
(4, 'zero') ironman
(5, 'thanos') ironman
(6, 'thar') ironman


In [46]:
for i in enumerate(t,start=2):
    print(i,j)

(2, 'superman') ironman
(3, 'spyderman') ironman
(4, 'hero') ironman
(5, 'zero') ironman
(6, 'thanos') ironman
(7, 'thar') ironman


In [47]:
for i, j in enumerate(t, start=2):
    print(i,j)

2 superman
3 spyderman
4 hero
5 zero
6 thanos
7 thar


In [48]:
for i, j in enumerate(t, start=100):
    print(i,j)


100 superman
101 spyderman
102 hero
103 zero
104 thanos
105 thar


In [49]:
for i , j in enumerate(t):
    print(i)


0
1
2
3
4
5


# Zip() Function
What is zip() function ?: Python Zip() method takes iterable or containers and returns a single iterable object , having mapping values from all the containers, it is used to map the similar index of multiple containers so that they can be used just a single entity. Syntax: Zip(*Iterable)

In [53]:
list1 = [1,2,3,4,5,6]
list2 = ['suraj','mayuresh','ganesh','kiran','vinay','mahesh']


In [55]:

l3=zip(list1,list2)

for i in l3:
    print(i)

(1, 'suraj')
(2, 'mayuresh')
(3, 'ganesh')
(4, 'kiran')
(5, 'vinay')
(6, 'mahesh')


In [56]:
list3 = list(zip(list1,list2))

In [57]:
list3

[(1, 'suraj'),
 (2, 'mayuresh'),
 (3, 'ganesh'),
 (4, 'kiran'),
 (5, 'vinay'),
 (6, 'mahesh')]

In [58]:
for i in list3:
    print(list3)

[(1, 'suraj'), (2, 'mayuresh'), (3, 'ganesh'), (4, 'kiran'), (5, 'vinay'), (6, 'mahesh')]
[(1, 'suraj'), (2, 'mayuresh'), (3, 'ganesh'), (4, 'kiran'), (5, 'vinay'), (6, 'mahesh')]
[(1, 'suraj'), (2, 'mayuresh'), (3, 'ganesh'), (4, 'kiran'), (5, 'vinay'), (6, 'mahesh')]
[(1, 'suraj'), (2, 'mayuresh'), (3, 'ganesh'), (4, 'kiran'), (5, 'vinay'), (6, 'mahesh')]
[(1, 'suraj'), (2, 'mayuresh'), (3, 'ganesh'), (4, 'kiran'), (5, 'vinay'), (6, 'mahesh')]
[(1, 'suraj'), (2, 'mayuresh'), (3, 'ganesh'), (4, 'kiran'), (5, 'vinay'), (6, 'mahesh')]


In [59]:
l1 = [1,2,3,4,5]
l2 = ['suraj','simon','mitra','hello','superman','ironman']

import pandas as pd

In [61]:
df = pd.DataFrame(zip(l1,l2), columns=['Roll.No','Name'])
df

Roll.No      Name
0        1     suraj
1        2     simon
2        3     mitra
3        4     hello
4        5  superman

In [62]:
list1 = [1,2,3,4,5]
list2 = ['suraj','ganesh','mayuresh','kiran','vinay']
list3 = [22,33,44,55,66]


In [63]:
df = pd.DataFrame(zip(list1,list2,list3), columns=['Roll.No','Name','Marks'])
df

Roll.No      Name  Marks
0        1     suraj     22
1        2    ganesh     33
2        3  mayuresh     44
3        4     kiran     55
4        5     vinay     66

In [64]:
print(df)

   Roll.No      Name  Marks
0        1     suraj     22
1        2    ganesh     33
2        3  mayuresh     44
3        4     kiran     55
4        5     vinay     66


In [65]:
list1 = [1,2,3,4,5]
list2 = ['suraj','ganesh','mayuresh','kiran','vinay']
list3 = ['English','History','Science','Maths','Marathi']
list4 = [22,33,44,55,66]
list5 = [100,100,100,100,100,100]

In [66]:
df = pd.DataFrame(zip(list1,list2,list3,list4,list5), columns=['Roll.No','Name','Subject','Marks','Total.Marks'])
df

Roll.No      Name  Subject  Marks  Total.Marks
0        1     suraj  English     22          100
1        2    ganesh  History     33          100
2        3  mayuresh  Science     44          100
3        4     kiran    Maths     55          100
4        5     vinay  Marathi     66          100

In [71]:
l1 = [1,2,3,4,5,6,7]
l2 = ['Hindi','English','Marathi','Science','Mathematics','History','Geography']
l3 = [59,78,69,70,121,66,71]
l4 = [100,100,100,100,150,100,100]
df = pd.DataFrame(zip(l1,l2,l3,l4), columns=['Serianl.No','Subject','Marks','Total.Marks'])
df

Serianl.No      Subject  Marks  Total.Marks
0           1        Hindi     59          100
1           2      English     78          100
2           3      Marathi     69          100
3           4      Science     70          100
4           5  Mathematics    121          150
5           6      History     66          100
6           7    Geography     71          100

In [76]:
df.loc['Total'] = df['Marks'].sum()
print(df)

       Serianl.No      Subject  Marks  Total.Marks
0               1        Hindi     59          100
1               2      English     78          100
2               3      Marathi     69          100
3               4      Science     70          100
4               5  Mathematics    121          150
5               6      History     66          100
6               7    Geography     71          100
Total        2136         2136   2136         2136


In [77]:
df= pd.DataFrame(df, columns=['subjects','Marks'])
print(df)

       subjects  Marks
0           NaN     59
1           NaN     78
2           NaN     69
3           NaN     70
4           NaN    121
5           NaN     66
6           NaN     71
Total       NaN   2136


In [78]:
l=[1,2,3,4,5,6,7,8,9,10]

f = lambda x:max(x)
print(f(l))

10


In [79]:
import pandas as pd

dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__deprecated_num_index_names',
 '__dir__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_testing',
 '_typing',
 '_ve

# Unpacking Nested Lists

In [80]:
l=[[1,2,3],[4,5,6],[7,8,9,10]]

In [81]:
[j for i in l for j in i]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [82]:
for i in l :
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10


In [83]:
t = ((1,2,3,4),(5,6,7,8),(9,10,11,12),(13,14,15,16))
[i for i in t]

[(1, 2, 3, 4), (5, 6, 7, 8), (9, 10, 11, 12), (13, 14, 15, 16)]

In [90]:
for i in t:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [96]:
t1 =(1,2,3,4,5)

In [99]:
[i for i in t1]

[1, 2, 3, 4, 5]

In [100]:
t = ((1,2,3,4),(5,6,7,8),(9,10,11,12))
t

((1, 2, 3, 4), (5, 6, 7, 8), (9, 10, 11, 12))

In [101]:
[j for i in t for j in i]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [104]:
l =[[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]]

In [105]:
[p for i in l for j in i for p in j]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [106]:
l = [["Hat","Glove","Google"],["Button","Zipper","Hook"]]
l[1][1][0]

'Z'

In [108]:
l[1][1][0:6]

'Zipper'

In [109]:
l =[{"Orange":"Orange"},{"Rose":"Red"},{"Violet":"Blue"}]
l[2]["Violet"]

'Blue'

In [111]:
d = {"dakar":{'weather':'Sunny','roads':'dry'}}
d['dakar']['roads']

'dry'

# Sort.Function()

In [117]:
l = [1,2,3,4,5,6,70,80,90,111,120,150,160,20,1000,1211,1511,1600]

In [118]:
l.sort()

In [119]:
l

[1, 2, 3, 4, 5, 6, 20, 70, 80, 90, 111, 120, 150, 160, 1000, 1211, 1511, 1600]

In [120]:
l.reverse()

In [121]:
l

[1600, 1511, 1211, 1000, 160, 150, 120, 111, 90, 80, 70, 20, 6, 5, 4, 3, 2, 1]

In [122]:
l.sort(reverse=True)

In [123]:
l

[1600, 1511, 1211, 1000, 160, 150, 120, 111, 90, 80, 70, 20, 6, 5, 4, 3, 2, 1]

In [124]:
l=[5,6,7,9,10,11,15,16,1,2,3,4,12,13,14,17,18,19,20,21,22,29,30,31,39,40,45]

In [126]:
l.sort()

In [127]:
l

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 29,
 30,
 31,
 39,
 40,
 45]

In [128]:
l.sort(reverse=False)

In [129]:
l


[1,
 2,
 3,
 4,
 5,
 6,
 7,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 29,
 30,
 31,
 39,
 40,
 45]

In [130]:
d1 = {'suraj':2,'hero':1,'spyderman':4,'thanos':3}
sorted(d1)

['hero', 'spyderman', 'suraj', 'thanos']

In [136]:
sorted(d1, reverse=True)

['thanos', 'suraj', 'spyderman', 'hero']

In [131]:
t =(1,4,2,8,9,2,3,6,5)

sorted(t)

[1, 2, 2, 3, 4, 5, 6, 8, 9]

In [133]:
t.sorted()

AttributeError: 'tuple' object has no attribute 'sorted'

In [134]:
l =[11,12,13,15,16,18,19,20,25,26,28,29,30,35,38,39,40]
sorted(l)

[11, 12, 13, 15, 16, 18, 19, 20, 25, 26, 28, 29, 30, 35, 38, 39, 40]

In [137]:
sorted(l,reverse=True)

[40, 39, 38, 35, 30, 29, 28, 26, 25, 20, 19, 18, 16, 15, 13, 12, 11]

In [138]:
sorted(l,reverse=False)

[11, 12, 13, 15, 16, 18, 19, 20, 25, 26, 28, 29, 30, 35, 38, 39, 40]

In [139]:
d=['suraj','hero','superman','thanos']


In [140]:
d

['suraj', 'hero', 'superman', 'thanos']

In [141]:
l=[1,2,3,-4,-6,-1000,-20]

In [142]:
f = lambda x:x<0

filter(f,l)


In [143]:
[i for i in l if i>0]

[1, 2, 3]

In [144]:
l=[1,2,3,4,5,6,7,7,8,9,9,9,9]

In [145]:
f = lambda x:x%2==0
list(filter(f,l))

[2, 4, 6, 8]

In [146]:
f = lambda x:x%1==0
list(filter(f,l))

[1, 2, 3, 4, 5, 6, 7, 7, 8, 9, 9, 9, 9]